apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      #securityContext:
      #  fsGroup: 1000 # www-data group ID
      #  runAsUser: 1000 # www-data user ID
      #  runAsGroup: 1000 # www-data group ID
      containers:
        - name: uptime-kuma
          image: elestio/uptime-kuma:1.23.16
          ports:
            - containerPort: 3001
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: uptime-kuma-data
              mountPath: /app/data
      volumes:
        - name: uptime-kuma-data
          persistentVolumeClaim:
            claimName: uptime-kuma-data-pvc
