apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:fizUvvoU90OR81o7v356NNhw72Mc/152TUJw+U8HAdAerhYk4fUBwUoMcGt98Ivi/WOeYJ7ODkycARAWCDdgjiDuUbX5Kh9ug0VyBWNIpP/rz4+/,iv:DrHbbHUoWR5MRE3MH3WNmZXCfLt0VWu4xrxj1QSqyUk=,tag:XTzMLNRg44Q2TsOIymtOHw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: renovate-container-env
sops:
    age:
        - recipient: age1zd7uc29r3kytkj3lxqn5l4tqy7jww5dha8vf77d0msfn63llkgxqrpu008
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1L3g2cWY1NDdDcjVSQWlu
            T244NHNmT0hrMDBOZWlHUEdZb3RrWVgzZnhjClBHK1NQM1d0UUphMVllRjhHVWto
            RW9UTXQxUFNUTC9UeTJZSEFtdzk5cEEKLS0tIGJQUU5Od2RTY0VMZm5KM1pRV21J
            bmJsZktxelhDemYxR3hzUVVEazYvY0kKo1XnJIUiPmo3qoSd/N6PQGOsyt0/kxzr
            JUA2dtxxdlVrHBX2h9ixJXjsS0aodJv6rzHW+QLpWSoMUX3uMbd8fA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-03T09:24:40Z"
    mac: ENC[AES256_GCM,data:7LNvcG5g3pjoTrbCaTXTwIWPsazl0LUEifoY7t1JEuJBGhiSewlS5LFR7wDGCKVkltOK/bYIWeROZGz/yTeAU9RIdyLuo4kSSthiKnA7Iji74tfUEdgvxsMneNRweIYfOXsw24M8/TxLGAUOR5dJu4RBL7iowQbjk1WXB+XAMLw=,iv:0ibxDFXCuEgxPAHLBaoQIqJzdfI5RRIjpL5TRgndJsM=,tag:pNxNVfoLRQB9DXSFhrF2PA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
