apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:94GNtUOSvOXGXSlMDDru0IDIYkpnOj970Sczbi+61G9bBcSoRs2bWcokiaSSMpyvM5t5gFv+Qk8=,iv:ZBRcM7P12hq/biLUaXT6Rby5J7bmjsLfHt9ajU66/5s=,tag:4tOZ6L90FZoSr7iph3hSaA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: renovate-container-env
sops:
    age:
        - recipient: age1zd7uc29r3kytkj3lxqn5l4tqy7jww5dha8vf77d0msfn63llkgxqrpu008
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVa05rYWZ1WnVxTE1tRGZV
            L0FlVnJWYW1DVXVXdkxmMHQ3QXpzT3pLM1ZNCncyK1lxdSthdWYrdkd1bFNjZXlJ
            cHRjcEhRN3ZzRzMxMmh5d0doYUlHK00KLS0tIFBFbnNsY2RxVkpmVWxia1owNWoy
            VDBzRjlCaUppbHNKUGgwNkMrZjhBWWsKmiodAjfNr6knO60UEtsxqxGITrCjiuEW
            30w0Zc7bnq/XkURXfmsVF5VlScPDO3aguY87mgkJwBBGGO7LZX1tSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-03T05:44:26Z"
    mac: ENC[AES256_GCM,data:9lyTp7RxMuuxFuVfyuYjg3OCfD7v2N0IzB6cRdDAsEdm55tkiDoLcq+3n/4H/BISsyohLRFuHqGb6VNoUqujupwx1gu8NW/oczIggk6Edb/J0HR7eBwzpr0F9f0XiMmasb6jXC32TNOirjPQg2q1qUihb645HZ62h+OobtLyGtY=,iv:tIw60fpHgezNn4CZPng3eOiYNDZBwiQJghtX5RIoufc=,tag:7C1HQiPPKweyoRuo7lY0vQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
